backend:
  name: github
  repo: your-github-username/Here-Comes-The-Bride
  branch: main
  base_url: https://api.netlify.com

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "src/data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Wedding Dresses", "Accessories", "Veils", "Shoes"]}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "In Stock", name: "inStock", widget: "boolean", default: true}
      - {label: "Size Options", name: "sizes", widget: "list", default: ["XS", "S", "M", "L", "XL"], required: false}
      - {label: "Colors", name: "colors", widget: "list", required: false} 